"""
Kaggle REST API client — bypasses the broken Python SDK.

The SDK's gRPC-style endpoints reject the new KGAT_ token format.
We use the REST API directly with Bearer auth, which works.

Usage:
    python scripts/kaggle_runner.py --config avr/configs/trace_lfm350m.yaml --no-poll
    python scripts/kaggle_runner.py --list
    python scripts/kaggle_runner.py --pull <kernel_slug>
"""

import argparse
import json
import os
import time
import sys
import shutil
import base64
import requests
from pathlib import Path
from datetime import datetime

KAGGLE_USERNAME = "Aryan111123"
KAGGLE_TOKEN = os.environ.get("KAGGLE_KEY", "KGAT_d0ce57c26cc6a601cc439857df913ff1")
KAGGLE_API = "https://www.kaggle.com/api/v1"
REPO_URL = "https://github.com/ARYAN2302/tiny-cl.git"


def kaggle_headers():
    return {"Authorization": f"Bearer {KAGGLE_TOKEN}"}


def generate_notebook(config_path: str, seed: int = None):
    """Generate a self-contained Kaggle notebook that runs one config."""
    config_name = Path(config_path).stem
    if seed:
        config_name += f"_s{seed}"

    notebook_code = f'''
# Auto-generated by kaggle_runner.py
# Config: {config_path}
# Seed: {seed}
# Generated: {datetime.now().isoformat()}

import subprocess, sys, os, json, shutil
from pathlib import Path

print("=== Installing dependencies ===")
subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                "transformers>=4.40", "peft>=0.10", "datasets>=2.14",
                "gdown>=4.7", "pyyaml>=6.0"], check=True)

print("=== Cloning tiny-cl ===")
if not os.path.exists("tiny-cl"):
    subprocess.run(["git", "clone", "-q", "{REPO_URL}"], check=True)
os.chdir("tiny-cl")
subprocess.run(["git", "pull", "-q"], check=False)

sys.path.insert(0, ".")

print("=== Running AVR config: {config_name} ===")
from avr.cli import run_from_config

config_path = "avr/configs/{Path(config_path).name}"
seed = {seed if seed else "None"}

results = run_from_config(config_path, seed)

print("\\n=== RESULTS ===")
print(json.dumps({{
    "metrics": results["metrics"],
    "total_repair_steps": results["total_repair_steps"],
    "tasks": results["tasks"],
    "seed": results["seed"],
}}, indent=2))

output_dir = Path("/kaggle/working/")
results_file = output_dir / "{config_name}_results.json"
src = f"results/{{Path(config_path).stem}}{{'_s' + str(seed) if seed else ''}}.json"
shutil.copy(src, results_file)
print(f"\\nResults saved to: {{results_file}}")
'''
    return notebook_code, config_name


def push_kernel(notebook_code: str, config_name: str) -> str:
    """Push kernel via REST API. Returns slug."""
    slug = f"{KAGGLE_USERNAME}/{config_name}"

    # Kaggle expects the code as base64
    code_b64 = base64.b64encode(notebook_code.encode()).decode()

    payload = {
        "text": "",
        "newTitle": config_name,
        "languageId": "python",
        "code": notebook_code,
        "kernelType": "script",
        "isPrivate": True,
        "enableGpu": True,
        "enableInternet": True,
        "datasetDataSources": [],
        "competitionDataSources": [],
        "kernelDataSources": [],
        "categoryIds": [],
    }

    print(f"Pushing kernel: {config_name}")
    # Try the push endpoint
    resp = requests.post(
        f"{KAGGLE_API}/kernels/push",
        headers={**kaggle_headers(), "Content-Type": "application/json"},
        json=payload,
    )

    if resp.status_code != 200:
        # Fall back to multipart form (older API)
        print(f"  JSON push failed ({resp.status_code}), trying multipart...")
        import io
        files = {
            "newTitle": (None, config_name),
            "languageId": (None, "python"),
            "code": (None, notebook_code),
            "kernelType": (None, "script"),
            "isPrivate": (None, "true"),
            "enableGpu": (None, "true"),
            "enableInternet": (None, "true"),
        }
        resp = requests.post(
            f"{KAGGLE_API}/kernels/push",
            headers=kaggle_headers(),
            files=files,
        )

    if resp.status_code == 200:
        data = resp.json()
        print(f"  Pushed: {data}")
        return slug
    else:
        print(f"  Push failed: {resp.status_code} {resp.text[:500]}")
        sys.exit(1)


def get_kernel_status(slug: str) -> str:
    """Get kernel status via REST."""
    resp = requests.get(
        f"{KAGGLE_API}/kernels/status",
        headers=kaggle_headers(),
        params={"user": KAGGLE_USERNAME, "kernelSlug": slug.split("/")[-1]},
    )
    if resp.status_code == 200:
        return resp.json()
    return {"status": "unknown", "error": resp.text[:200]}


def poll_kernel(slug: str, timeout: int = 43200) -> str:
    """Poll until kernel completes."""
    start = time.time()
    last_status = None
    kernel_slug = slug.split("/")[-1]
    while time.time() - start < timeout:
        try:
            resp = requests.get(
                f"{KAGGLE_API}/kernels/status",
                headers=kaggle_headers(),
                params={"user": KAGGLE_USERNAME, "kernelSlug": kernel_slug},
            )
            if resp.status_code == 200:
                data = resp.json()
                status = data.get("status", "unknown")
                if status != last_status:
                    elapsed = int(time.time() - start)
                    print(f"  [{elapsed}s] {slug}: {status}")
                    last_status = status
                if status in ["complete", "error", "cancelled"]:
                    return status
            else:
                print(f"  poll error: {resp.status_code}")
        except Exception as e:
            print(f"  poll error: {e}")
        time.sleep(60)
    return "timeout"


def pull_results(slug: str, config_name: str):
    """Pull kernel output."""
    output_dir = Path(f"/tmp/kaggle_output_{config_name}")
    output_dir.mkdir(exist_ok=True)
    kernel_slug = slug.split("/")[-1]
    print(f"Pulling output for {slug}...")

    # Download as a zip
    resp = requests.get(
        f"{KAGGLE_API}/kernels/output",
        headers=kaggle_headers(),
        params={"user": KAGGLE_USERNAME, "kernelSlug": kernel_slug},
        stream=True,
    )
    if resp.status_code == 200:
        zip_path = output_dir / "output.zip"
        with open(zip_path, "wb") as f:
            for chunk in resp.iter_content(chunk_size=8192):
                f.write(chunk)
        import zipfile
        with zipfile.ZipFile(zip_path, "r") as z:
            z.extractall(output_dir)
        print(f"  Extracted to {output_dir}")

        results_dir = Path("avr/results")
        results_dir.mkdir(parents=True, exist_ok=True)
        for f in output_dir.glob("*.json"):
            dest = results_dir / f.name
            shutil.copy(f, dest)
            print(f"  Saved: {dest}")
            return dest
        print("  No results JSON found in output")
    else:
        print(f"  Pull failed: {resp.status_code} {resp.text[:200]}")
    return None


def list_kernels():
    """List user's kernels."""
    resp = requests.get(
        f"{KAGGLE_API}/kernels/list",
        headers=kaggle_headers(),
        params={"user": KAGGLE_USERNAME, "page_size": 20},
    )
    if resp.status_code == 200:
        kernels = resp.json()
        if isinstance(kernels, list):
            for k in kernels:
                print(f"  {k.get('ref','?')} | {k.get('status','?')} | {k.get('title','?')}")
        else:
            print(json.dumps(kernels, indent=2)[:500])
    else:
        print(f"List failed: {resp.status_code} {resp.text[:300]}")


def main():
    parser = argparse.ArgumentParser(description="Kaggle runner for avr-cl")
    parser.add_argument("--config", help="Path to YAML config")
    parser.add_argument("--seed", type=int, default=None)
    parser.add_argument("--list", action="store_true")
    parser.add_argument("--pull", help="Pull results for a kernel slug")
    parser.add_argument("--no-poll", action="store_true")
    args = parser.parse_args()

    if args.list:
        list_kernels()
        return

    if args.pull:
        config_name = args.pull.split("/")[-1]
        pull_results(args.pull, config_name)
        return

    if not args.config:
        parser.error("--config required (or use --list / --pull)")

    notebook_code, config_name = generate_notebook(args.config, args.seed)
    print(f"Generated notebook for: {config_name}")

    slug = push_kernel(notebook_code, config_name)

    if args.no_poll:
        print(f"\nKernel pushed: {slug}")
        print(f"Poll: python {sys.argv[0]} --pull {slug}")
        return

    print(f"\nPolling {slug}...")
    status = poll_kernel(slug)

    if status == "complete":
        print(f"\n✓ Complete. Pulling results...")
        pull_results(slug, config_name)
    else:
        print(f"\n✗ Status: {status}")


if __name__ == "__main__":
    main()
