"""
Kaggle automation via the kaggle CLI (the REST endpoint is broken for pushes,
but the CLI works).

Usage:
    python scripts/kaggle_runner.py --config avr/configs/trace_lfm350m.yaml --no-poll
    python scripts/kaggle_runner.py --config avr/configs/trace_lfm350m.yaml --seed 123
    python scripts/kaggle_runner.py --list
    python scripts/kaggle_runner.py --status <kernel_slug>
    python scripts/kaggle_runner.py --pull <kernel_slug>
"""

import argparse
import json
import os
import time
import sys
import shutil
import subprocess
from pathlib import Path
from datetime import datetime

KAGGLE_USERNAME = "aryan111123"
KAGGLE_KEY = os.environ.get("KAGGLE_KEY", "3dd3ca5514175b9eb32dae8773b8750d")
REPO_URL = "https://github.com/ARYAN2302/tiny-cl.git"
KAGGLE_CLI = "/home/z/.venv/bin/kaggle"


def kaggle_env():
    env = os.environ.copy()
    env["KAGGLE_USERNAME"] = KAGGLE_USERNAME
    env["KAGGLE_KEY"] = KAGGLE_KEY
    return env


def generate_notebook(config_path: str, seed: int = None):
    """Generate a self-contained Kaggle notebook that runs one config."""
    config_name = Path(config_path).stem
    if seed:
        config_name += f"_s{seed}"

    notebook_code = f'''
# Auto-generated by kaggle_runner.py
# Config: {config_path}
# Seed: {seed}
# Generated: {datetime.now().isoformat()}

import subprocess, sys, os, json, shutil, traceback
from pathlib import Path

LOG_FILE = Path("/kaggle/working/run_log.txt")
LOG_FILE.parent.mkdir(parents=True, exist_ok=True)

def log(msg):
    print(msg, flush=True)
    with open(LOG_FILE, "a") as f:
        f.write(msg + "\\n")

try:
    log("=== Installing dependencies ===")
    # Don't upgrade torch — Kaggle's pre-installed torch is compiled for the T4's
    # CUDA driver. Upgrading pulls a torch built for a different CUDA, causing
    # "no kernel image available" errors. Only install what's missing.
    subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                    "peft>=0.10", "datasets>=2.14",
                    "gdown>=4.7", "pyyaml>=6.0"], check=True)
    # torchao needs to be compatible with Kaggle's torch — install the version
    # that matches, or skip it if PEFT can work without it
    subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                    "torchao>=0.16.0",
                    "--no-deps"], check=False)  # no-deps so it doesn't touch torch

    log("=== Cloning tiny-cl ===")
    if not os.path.exists("tiny-cl"):
        subprocess.run(["git", "clone", "-q", "{REPO_URL}"], check=True)
    os.chdir("tiny-cl")
    subprocess.run(["git", "pull", "-q"], check=False)

    sys.path.insert(0, ".")

    log("=== Verifying avr package imports ===")
    from avr.cli import run_from_config
    from avr.framework import ContinualPostTrainer
    from avr.strategy import AVRStrategy
    log("  all imports OK")

    log("=== Running AVR config: {config_name} ===")
    config_path = "avr/configs/{Path(config_path).name}"
    seed = {seed if seed else "None"}

    results = run_from_config(config_path, seed)

    log("\\n=== RESULTS ===")
    log(json.dumps({{
        "metrics": results["metrics"],
        "total_repair_steps": results["total_repair_steps"],
        "tasks": results["tasks"],
        "seed": results["seed"],
    }}, indent=2))

    output_dir = Path("/kaggle/working/")
    results_file = output_dir / "{config_name}_results.json"
    src = f"results/{{Path(config_path).stem}}{{'_s' + str(seed) if seed else ''}}.json"
    shutil.copy(src, results_file)
    log(f"\\nResults saved to: {{results_file}}")

except Exception as e:
    log(f"\\n=== FATAL ERROR ===")
    log(f"{{type(e).__name__}}: {{e}}")
    log("\\nFull traceback:")
    log(traceback.format_exc())
    # Still write the log file so we can pull it
    shutil.copy(LOG_FILE, Path("/kaggle/working/run_log.txt"))
    raise
'''
    return notebook_code, config_name


def push_kernel(notebook_code: str, config_name: str) -> str:
    """Push kernel via kaggle CLI. Returns slug."""
    kernel_dir = Path(f"/tmp/kaggle_kernel_{config_name}")
    if kernel_dir.exists():
        shutil.rmtree(kernel_dir)
    kernel_dir.mkdir(parents=True)

    (kernel_dir / f"{config_name}.py").write_text(notebook_code)

    meta = {
        "id": f"{KAGGLE_USERNAME}/{config_name}",
        "title": config_name,
        "code_file": f"{config_name}.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": True,
        "enable_gpu": True,
        "enable_internet": True,
        "dataset_sources": [],
        "competition_sources": [],
        "kernel_sources": [],
    }
    (kernel_dir / "kernel-metadata.json").write_text(json.dumps(meta, indent=2))

    print(f"Pushing kernel: {config_name}")
    result = subprocess.run(
        [KAGGLE_CLI, "kernels", "push", "-p", str(kernel_dir)],
        capture_output=True, text=True, env=kaggle_env(),
    )
    print(f"  {result.stdout.strip()}")
    if result.returncode != 0:
        print(f"  ERROR: {result.stderr[:300]}")
        sys.exit(1)

    slug = f"{KAGGLE_USERNAME}/{config_name}"
    return slug


def get_status(slug: str) -> str:
    """Get kernel status via CLI."""
    kernel_slug = slug.split("/")[-1]
    result = subprocess.run(
        [KAGGLE_CLI, "kernels", "status", slug],
        capture_output=True, text=True, env=kaggle_env(),
    )
    return result.stdout.strip() + " " + result.stderr.strip()


def poll_kernel(slug: str, timeout: int = 43200) -> str:
    """Poll until kernel completes."""
    start = time.time()
    last_status = None
    while time.time() - start < timeout:
        status_str = get_status(slug)
        if status_str != last_status:
            elapsed = int(time.time() - start)
            print(f"  [{elapsed}s] {status_str}")
            last_status = status_str
        # Statuses: "running", "complete", "error", "cancelled"
        if "complete" in status_str.lower():
            return "complete"
        if "error" in status_str.lower() or "cancel" in status_str.lower():
            return "error"
        time.sleep(120)  # check every 2 min
    return "timeout"


def pull_results(slug: str, config_name: str):
    """Pull kernel output."""
    output_dir = Path(f"/tmp/kaggle_output_{config_name}")
    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True)

    print(f"Pulling output for {slug}...")
    result = subprocess.run(
        [KAGGLE_CLI, "kernels", "output", slug, "-p", str(output_dir)],
        capture_output=True, text=True, env=kaggle_env(),
    )
    if result.returncode != 0:
        print(f"  Pull failed: {result.stderr[:300]}")
        return None

    results_dir = Path("avr/results")
    results_dir.mkdir(parents=True, exist_ok=True)
    for f in output_dir.glob("*.json"):
        dest = results_dir / f.name
        shutil.copy(f, dest)
        print(f"  Saved: {dest}")
        return dest
    print("  No results JSON found in output")
    # List what we got
    for f in output_dir.iterdir():
        print(f"  Found: {f.name}")
    return None


def list_kernels():
    """List user's kernels."""
    result = subprocess.run(
        [KAGGLE_CLI, "kernels", "list", "--user", KAGGLE_USERNAME,
         "--page-size", "20"],
        capture_output=True, text=True, env=kaggle_env(),
    )
    print(result.stdout)
    if result.stderr:
        print(result.stderr[:300], file=sys.stderr)


def main():
    parser = argparse.ArgumentParser(description="Kaggle runner for avr-cl")
    parser.add_argument("--config", help="Path to YAML config")
    parser.add_argument("--seed", type=int, default=None)
    parser.add_argument("--list", action="store_true")
    parser.add_argument("--status", help="Get status for a kernel slug")
    parser.add_argument("--pull", help="Pull results for a kernel slug")
    parser.add_argument("--no-poll", action="store_true",
                        help="Push and exit, don't wait")
    args = parser.parse_args()

    if args.list:
        list_kernels()
        return

    if args.status:
        print(get_status(args.status))
        return

    if args.pull:
        config_name = args.pull.split("/")[-1]
        pull_results(args.pull, config_name)
        return

    if not args.config:
        parser.error("--config required (or use --list / --status / --pull)")

    notebook_code, config_name = generate_notebook(args.config, args.seed)
    print(f"Generated notebook for: {config_name}")

    slug = push_kernel(notebook_code, config_name)
    print(f"Slug: {slug}")
    print(f"Monitor: https://www.kaggle.com/code/{slug}")

    if args.no_poll:
        print(f"\nKernel pushed. Check status with:")
        print(f"  python {sys.argv[0]} --status {slug}")
        print(f"Pull results with:")
        print(f"  python {sys.argv[0]} --pull {slug}")
        return

    print(f"\nPolling {slug} (up to 12h)...")
    status = poll_kernel(slug)

    if status == "complete":
        print(f"\n✓ Complete. Pulling results...")
        results_path = pull_results(slug, config_name)
        if results_path:
            print(f"\nResults: {results_path}")
            with open(results_path) as f:
                data = json.load(f)
            print(f"\n=== SUMMARY ===")
            print(json.dumps({
                "metrics": data.get("metrics"),
                "total_repair_steps": data.get("total_repair_steps"),
                "seed": data.get("seed"),
            }, indent=2))
    else:
        print(f"\n✗ Status: {status}")


if __name__ == "__main__":
    main()
